/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE inventory-requestBaseService PLEASE EDIT ../inventory-request.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { InventoryRequest } from '../../domain/mystore_db/inventory-request';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../InventoryRequest.service.ts
 */

/*
 * SCHEMA DB InventoryRequest
 *
	{
		CostPrice: {
			type: 'Decimal'
		},
		ProductName: {
			type: 'String'
		},
		PurchaseDate: {
			type: 'Date'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class InventoryRequestBaseService {

    contextUrl: string = environment.endpoint + '/inventoryrequest';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * InventoryRequestService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: InventoryRequest): Observable<InventoryRequest> {
        return this.http
            .post<InventoryRequest>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * InventoryRequestService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * InventoryRequestService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<InventoryRequest> {
        return this.http
            .get<InventoryRequest>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * InventoryRequestService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<InventoryRequest[]> {
        return this.http
            .get<InventoryRequest[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * InventoryRequestService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: InventoryRequest): Observable<InventoryRequest> {
        return this.http
            .post<InventoryRequest>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
